pdns.index:
    path:     /
    defaults: { _controller: PdnsBundle:Pdns:zoneList }
pdns.zonelist:
    path:     /pdns/zones
    defaults: { _controller: PdnsBundle:Pdns:zoneList }
pdns.recordlist:
    path:     /pdns/zones/{zone_id}
    defaults: { _controller: PdnsBundle:Pdns:recordList }
pdns.updaterecord:
    path:     /pdns/record/update
    defaults: { _controller: PdnsBundle:Pdns:update }
pdns.createrecord:
    path:     /pdns/record/create
    defaults: { _controller: PdnsBundle:Pdns:create }
pdns.deleterecord:
    path:     /pdns/record/delete
    defaults: { _controller: PdnsBundle:Pdns:delete }
pdns.newzone:
    path:    /pdns/zone/create
    defaults: {_controller:Shiningw\PdnsBundle\Controller\PdnsController::newZone }
pdns.removezone:
    path:    /pdns/zone/remove
    defaults: {_controller:Shiningw\PdnsBundle\Controller\PdnsController::removeZone }
pdns.search:
    path:    /pdns/zone/remove
    defaults: {_controller:Shiningw\PdnsBundle\Controller\PdnsController::search}
